### ISSUE TITLE
y ahora la mejor parte

### ISSUE THREAD

**Issue by rjdelrio** [Tomizaky/Prueba#23]
issue ```TypeError y ValueError y KeyError``` muy buena

**Comment by Tomizaky** [comment]
https://stackoverflow.com/questions/43556422/angular-2-typeerror-cannot-read-property-apply-of-undefined

**Comment by Tomizaky** [comment]
https://stackoverflow.com/questions/4393268/how-to-raise-a-valueerror

**Comment by Tomizaky** [comment]
https://stackoverflow.com/questions/10116518/im-getting-key-error-in-python

**Comment by rjdelrio** [comment]
buenos link me encantan

**Comment by Tomizaky** [comment]
boa manito
